services:
  foodbox-backend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - TZ=Asia/Seoul
      - SLACK_TOKEN=${SLACK_TOKEN}
      - SLACK_CHANNEL=${SLACK_CHANNEL}
      - DB_FILE_DIR=/db
      - CRAWL_URL=${CRAWL_URL}
    volumes:
      - ./db:/db
    networks:
      - foodbox-network

  foodbox-frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - foodbox-backend
    networks:
      - foodbox-network

networks:
  foodbox-network:
    driver: bridge
