spring:
  application:
    name: foodbox

crawl:
  crawl-url: https://daejeonyuseong.modoo.at/?link=8dpmx8ms
  css-selector: .gallery_img img
  image-index: 1

slack:
  slack-token: ${SLACK_TOKEN:"YOUR_SLACK_TOKEN_HERE"}
  slack-channel: ${SLACK_CHANNEL:"YOUR_SLACK_CHANNEL_HERE"}
  user-name: "점심봇"
  slack-url: "https://hooks.slack.com/services"

server:
  port: 80
