spring:
  application:
    name: foodbox
foodbox:
  db-file-dir: ${DB_FILE_DIR:"/foodbox/db"}

crawl:
  crawl-url: ${CRAWL_URL:http://www.msmfood.co.kr/page/sub2_7}

slack:
  slack-token: ${SLACK_TOKEN:"YOUR_SLACK_TOKEN_HERE"}
  slack-channel: ${SLACK_CHANNEL:"YOUR_SLACK_CHANNEL_HERE"}
  user-name: "점심봇"
  slack-url: "https://hooks.slack.com/services"

server:
  port: 80
